

module Yoga
  class Expression
    module Parser
      # This file assumes that the output of the generator will be placed
# within a module or a class.  However, the module/class requires a
# `type` method, which takes a terminal and gives its type, as a
# symbol.  These types should line up with the terminals that were
# defined in the original grammar.

# The actions to take during parsing.  In every state, there are a
# set of acceptable peek tokens; this table tells the parser what
# to do on each acceptable peek token.  The possible actions include
# `:accept`, `:reduce`, and `:state`; `:accept` means to accept the
# input and return the value of the pasing.  `:reduce` means to
# reduce the top of the stack into a given nonterminal.  `:state`
# means to transition to another state.
#
# @return [Array<Hash<(Symbol, Array<(Symbol, Numeric)>)>>]
ACTION_TABLE = [{:expression=>[:state, 1],
  :group=>[:state, 2],
  :value=>[:state, 3],
  :LPAREN=>[:state, 4],
  :STRING=>[:state, 5],
  :contain=>[:state, 6],
  :NUMBER=>[:state, 7],
  :identifier=>[:state, 8],
  :LBRACK=>[:state, 9],
  :CHARACTER=>[:state, 10]},
 {:"$"=>[:state, 11]},
 {:expression=>[:state, 12],
  :group=>[:state, 2],
  :value=>[:state, 3],
  :LPAREN=>[:state, 4],
  :STRING=>[:state, 5],
  :contain=>[:state, 6],
  :NUMBER=>[:state, 7],
  :identifier=>[:state, 8],
  :LBRACK=>[:state, 9],
  :CHARACTER=>[:state, 10],
  :modifier=>[:state, 13],
  :STAR=>[:state, 14],
  :PLUS=>[:state, 15],
  :OPTIONAL=>[:state, 16],
  :binop=>[:state, 17],
  :UNION=>[:state, 18],
  :INTERSECT=>[:state, 19],
  :SDIFFERENCE=>[:state, 20],
  :DIFFERENCE=>[:state, 21],
  :"$"=>[:reduce, 1],
  :RPAREN=>[:reduce, 1]},
 {:"$"=>[:reduce, 5],
  :STAR=>[:reduce, 5],
  :PLUS=>[:reduce, 5],
  :OPTIONAL=>[:reduce, 5],
  :UNION=>[:reduce, 5],
  :INTERSECT=>[:reduce, 5],
  :SDIFFERENCE=>[:reduce, 5],
  :DIFFERENCE=>[:reduce, 5],
  :LPAREN=>[:reduce, 5],
  :STRING=>[:reduce, 5],
  :LBRACK=>[:reduce, 5],
  :NUMBER=>[:reduce, 5],
  :CHARACTER=>[:reduce, 5],
  :RPAREN=>[:reduce, 5]},
 {:expression=>[:state, 22],
  :group=>[:state, 2],
  :value=>[:state, 3],
  :LPAREN=>[:state, 4],
  :STRING=>[:state, 5],
  :contain=>[:state, 6],
  :NUMBER=>[:state, 7],
  :identifier=>[:state, 8],
  :LBRACK=>[:state, 9],
  :CHARACTER=>[:state, 10]},
 {:"$"=>[:reduce, 14],
  :STAR=>[:reduce, 14],
  :PLUS=>[:reduce, 14],
  :OPTIONAL=>[:reduce, 14],
  :UNION=>[:reduce, 14],
  :INTERSECT=>[:reduce, 14],
  :SDIFFERENCE=>[:reduce, 14],
  :DIFFERENCE=>[:reduce, 14],
  :LPAREN=>[:reduce, 14],
  :STRING=>[:reduce, 14],
  :LBRACK=>[:reduce, 14],
  :NUMBER=>[:reduce, 14],
  :CHARACTER=>[:reduce, 14],
  :RPAREN=>[:reduce, 14]},
 {:"$"=>[:reduce, 15],
  :STAR=>[:reduce, 15],
  :PLUS=>[:reduce, 15],
  :OPTIONAL=>[:reduce, 15],
  :UNION=>[:reduce, 15],
  :INTERSECT=>[:reduce, 15],
  :SDIFFERENCE=>[:reduce, 15],
  :DIFFERENCE=>[:reduce, 15],
  :LPAREN=>[:reduce, 15],
  :STRING=>[:reduce, 15],
  :LBRACK=>[:reduce, 15],
  :NUMBER=>[:reduce, 15],
  :CHARACTER=>[:reduce, 15],
  :RPAREN=>[:reduce, 15]},
 {:"$"=>[:reduce, 16],
  :STAR=>[:reduce, 16],
  :PLUS=>[:reduce, 16],
  :OPTIONAL=>[:reduce, 16],
  :UNION=>[:reduce, 16],
  :INTERSECT=>[:reduce, 16],
  :SDIFFERENCE=>[:reduce, 16],
  :DIFFERENCE=>[:reduce, 16],
  :LPAREN=>[:reduce, 16],
  :STRING=>[:reduce, 16],
  :LBRACK=>[:reduce, 16],
  :NUMBER=>[:reduce, 16],
  :CHARACTER=>[:reduce, 16],
  :RPAREN=>[:reduce, 16]},
 {:"$"=>[:reduce, 17],
  :STAR=>[:reduce, 17],
  :PLUS=>[:reduce, 17],
  :OPTIONAL=>[:reduce, 17],
  :UNION=>[:reduce, 17],
  :INTERSECT=>[:reduce, 17],
  :SDIFFERENCE=>[:reduce, 17],
  :DIFFERENCE=>[:reduce, 17],
  :LPAREN=>[:reduce, 17],
  :STRING=>[:reduce, 17],
  :LBRACK=>[:reduce, 17],
  :NUMBER=>[:reduce, 17],
  :CHARACTER=>[:reduce, 17],
  :RPAREN=>[:reduce, 17]},
 {:"contain.parts"=>[:state, 23],
  :"contain.part"=>[:state, 24],
  :"contain.char"=>[:state, 25],
  :DIFFERENCE=>[:state, 26],
  :CHARACTER=>[:state, 27],
  :NUMBER=>[:state, 28],
  :ESCAPED=>[:state, 29]},
 {:chars=>[:state, 30],
  :char=>[:state, 31],
  :CHARACTER=>[:state, 32],
  :NUMBER=>[:state, 33],
  :DIFFERENCE=>[:state, 34]},
 {:"$"=>[:accept, 0]},
 {:"$"=>[:reduce, 2], :RPAREN=>[:reduce, 2]},
 {:"$"=>[:reduce, 3],
  :STAR=>[:reduce, 3],
  :PLUS=>[:reduce, 3],
  :OPTIONAL=>[:reduce, 3],
  :UNION=>[:reduce, 3],
  :INTERSECT=>[:reduce, 3],
  :SDIFFERENCE=>[:reduce, 3],
  :DIFFERENCE=>[:reduce, 3],
  :LPAREN=>[:reduce, 3],
  :STRING=>[:reduce, 3],
  :LBRACK=>[:reduce, 3],
  :NUMBER=>[:reduce, 3],
  :CHARACTER=>[:reduce, 3],
  :RPAREN=>[:reduce, 3]},
 {:"$"=>[:reduce, 6],
  :STAR=>[:reduce, 6],
  :PLUS=>[:reduce, 6],
  :OPTIONAL=>[:reduce, 6],
  :UNION=>[:reduce, 6],
  :INTERSECT=>[:reduce, 6],
  :SDIFFERENCE=>[:reduce, 6],
  :DIFFERENCE=>[:reduce, 6],
  :LPAREN=>[:reduce, 6],
  :STRING=>[:reduce, 6],
  :LBRACK=>[:reduce, 6],
  :NUMBER=>[:reduce, 6],
  :CHARACTER=>[:reduce, 6],
  :RPAREN=>[:reduce, 6]},
 {:"$"=>[:reduce, 7],
  :STAR=>[:reduce, 7],
  :PLUS=>[:reduce, 7],
  :OPTIONAL=>[:reduce, 7],
  :UNION=>[:reduce, 7],
  :INTERSECT=>[:reduce, 7],
  :SDIFFERENCE=>[:reduce, 7],
  :DIFFERENCE=>[:reduce, 7],
  :LPAREN=>[:reduce, 7],
  :STRING=>[:reduce, 7],
  :LBRACK=>[:reduce, 7],
  :NUMBER=>[:reduce, 7],
  :CHARACTER=>[:reduce, 7],
  :RPAREN=>[:reduce, 7]},
 {:"$"=>[:reduce, 8],
  :STAR=>[:reduce, 8],
  :PLUS=>[:reduce, 8],
  :OPTIONAL=>[:reduce, 8],
  :UNION=>[:reduce, 8],
  :INTERSECT=>[:reduce, 8],
  :SDIFFERENCE=>[:reduce, 8],
  :DIFFERENCE=>[:reduce, 8],
  :LPAREN=>[:reduce, 8],
  :STRING=>[:reduce, 8],
  :LBRACK=>[:reduce, 8],
  :NUMBER=>[:reduce, 8],
  :CHARACTER=>[:reduce, 8],
  :RPAREN=>[:reduce, 8]},
 {:group=>[:state, 35],
  :value=>[:state, 3],
  :LPAREN=>[:state, 4],
  :STRING=>[:state, 5],
  :contain=>[:state, 6],
  :NUMBER=>[:state, 7],
  :identifier=>[:state, 8],
  :LBRACK=>[:state, 9],
  :CHARACTER=>[:state, 10]},
 {:STAR=>[:reduce, 9],
  :PLUS=>[:reduce, 9],
  :OPTIONAL=>[:reduce, 9],
  :UNION=>[:reduce, 9],
  :INTERSECT=>[:reduce, 9],
  :SDIFFERENCE=>[:reduce, 9],
  :DIFFERENCE=>[:reduce, 9],
  :LPAREN=>[:reduce, 9],
  :STRING=>[:reduce, 9],
  :LBRACK=>[:reduce, 9],
  :NUMBER=>[:reduce, 9],
  :CHARACTER=>[:reduce, 9]},
 {:STAR=>[:reduce, 10],
  :PLUS=>[:reduce, 10],
  :OPTIONAL=>[:reduce, 10],
  :UNION=>[:reduce, 10],
  :INTERSECT=>[:reduce, 10],
  :SDIFFERENCE=>[:reduce, 10],
  :DIFFERENCE=>[:reduce, 10],
  :LPAREN=>[:reduce, 10],
  :STRING=>[:reduce, 10],
  :LBRACK=>[:reduce, 10],
  :NUMBER=>[:reduce, 10],
  :CHARACTER=>[:reduce, 10]},
 {:STAR=>[:reduce, 11],
  :PLUS=>[:reduce, 11],
  :OPTIONAL=>[:reduce, 11],
  :UNION=>[:reduce, 11],
  :INTERSECT=>[:reduce, 11],
  :SDIFFERENCE=>[:reduce, 11],
  :DIFFERENCE=>[:reduce, 11],
  :LPAREN=>[:reduce, 11],
  :STRING=>[:reduce, 11],
  :LBRACK=>[:reduce, 11],
  :NUMBER=>[:reduce, 11],
  :CHARACTER=>[:reduce, 11]},
 {:STAR=>[:reduce, 12],
  :PLUS=>[:reduce, 12],
  :OPTIONAL=>[:reduce, 12],
  :UNION=>[:reduce, 12],
  :INTERSECT=>[:reduce, 12],
  :SDIFFERENCE=>[:reduce, 12],
  :DIFFERENCE=>[:reduce, 12],
  :LPAREN=>[:reduce, 12],
  :STRING=>[:reduce, 12],
  :LBRACK=>[:reduce, 12],
  :NUMBER=>[:reduce, 12],
  :CHARACTER=>[:reduce, 12]},
 {:RPAREN=>[:state, 36]},
 {:RBRACK=>[:state, 37]},
 {:"contain.parts"=>[:state, 38],
  :"contain.part"=>[:state, 24],
  :"contain.char"=>[:state, 25],
  :DIFFERENCE=>[:state, 26],
  :CHARACTER=>[:state, 27],
  :NUMBER=>[:state, 28],
  :ESCAPED=>[:state, 29],
  :RBRACK=>[:reduce, 25]},
 {:DIFFERENCE=>[:state, 39],
  :RBRACK=>[:reduce, 27],
  :CHARACTER=>[:reduce, 27],
  :NUMBER=>[:reduce, 27],
  :ESCAPED=>[:reduce, 27]},
 {:RBRACK=>[:reduce, 29],
  :CHARACTER=>[:reduce, 29],
  :NUMBER=>[:reduce, 29],
  :ESCAPED=>[:reduce, 29],
  :DIFFERENCE=>[:reduce, 29]},
 {:RBRACK=>[:reduce, 30],
  :CHARACTER=>[:reduce, 30],
  :NUMBER=>[:reduce, 30],
  :ESCAPED=>[:reduce, 30],
  :DIFFERENCE=>[:reduce, 30]},
 {:RBRACK=>[:reduce, 31],
  :CHARACTER=>[:reduce, 31],
  :NUMBER=>[:reduce, 31],
  :ESCAPED=>[:reduce, 31],
  :DIFFERENCE=>[:reduce, 31]},
 {:RBRACK=>[:reduce, 32],
  :CHARACTER=>[:reduce, 32],
  :NUMBER=>[:reduce, 32],
  :ESCAPED=>[:reduce, 32],
  :DIFFERENCE=>[:reduce, 32]},
 {:"$"=>[:reduce, 19],
  :STAR=>[:reduce, 19],
  :PLUS=>[:reduce, 19],
  :OPTIONAL=>[:reduce, 19],
  :UNION=>[:reduce, 19],
  :INTERSECT=>[:reduce, 19],
  :SDIFFERENCE=>[:reduce, 19],
  :DIFFERENCE=>[:reduce, 19],
  :LPAREN=>[:reduce, 19],
  :STRING=>[:reduce, 19],
  :LBRACK=>[:reduce, 19],
  :NUMBER=>[:reduce, 19],
  :CHARACTER=>[:reduce, 19],
  :RPAREN=>[:reduce, 19]},
 {:chars=>[:state, 40],
  :char=>[:state, 31],
  :CHARACTER=>[:state, 32],
  :NUMBER=>[:state, 33],
  :DIFFERENCE=>[:state, 34],
  :"$"=>[:reduce, 20],
  :STAR=>[:reduce, 20],
  :PLUS=>[:reduce, 20],
  :OPTIONAL=>[:reduce, 20],
  :UNION=>[:reduce, 20],
  :INTERSECT=>[:reduce, 20],
  :SDIFFERENCE=>[:reduce, 20],
  :LPAREN=>[:reduce, 20],
  :STRING=>[:reduce, 20],
  :LBRACK=>[:reduce, 20],
  :RPAREN=>[:reduce, 20]},
 {:"$"=>[:reduce, 22],
  :STAR=>[:reduce, 22],
  :PLUS=>[:reduce, 22],
  :OPTIONAL=>[:reduce, 22],
  :UNION=>[:reduce, 22],
  :INTERSECT=>[:reduce, 22],
  :SDIFFERENCE=>[:reduce, 22],
  :DIFFERENCE=>[:reduce, 22],
  :LPAREN=>[:reduce, 22],
  :STRING=>[:reduce, 22],
  :LBRACK=>[:reduce, 22],
  :NUMBER=>[:reduce, 22],
  :CHARACTER=>[:reduce, 22],
  :RPAREN=>[:reduce, 22]},
 {:"$"=>[:reduce, 23],
  :STAR=>[:reduce, 23],
  :PLUS=>[:reduce, 23],
  :OPTIONAL=>[:reduce, 23],
  :UNION=>[:reduce, 23],
  :INTERSECT=>[:reduce, 23],
  :SDIFFERENCE=>[:reduce, 23],
  :DIFFERENCE=>[:reduce, 23],
  :LPAREN=>[:reduce, 23],
  :STRING=>[:reduce, 23],
  :LBRACK=>[:reduce, 23],
  :NUMBER=>[:reduce, 23],
  :CHARACTER=>[:reduce, 23],
  :RPAREN=>[:reduce, 23]},
 {:"$"=>[:reduce, 24],
  :STAR=>[:reduce, 24],
  :PLUS=>[:reduce, 24],
  :OPTIONAL=>[:reduce, 24],
  :UNION=>[:reduce, 24],
  :INTERSECT=>[:reduce, 24],
  :SDIFFERENCE=>[:reduce, 24],
  :DIFFERENCE=>[:reduce, 24],
  :LPAREN=>[:reduce, 24],
  :STRING=>[:reduce, 24],
  :LBRACK=>[:reduce, 24],
  :NUMBER=>[:reduce, 24],
  :CHARACTER=>[:reduce, 24],
  :RPAREN=>[:reduce, 24]},
 {:modifier=>[:state, 13],
  :STAR=>[:state, 14],
  :PLUS=>[:state, 15],
  :OPTIONAL=>[:state, 16],
  :binop=>[:state, 17],
  :UNION=>[:state, 18],
  :INTERSECT=>[:state, 19],
  :SDIFFERENCE=>[:state, 20],
  :DIFFERENCE=>[:state, 21],
  :"$"=>[:reduce, 4],
  :LPAREN=>[:reduce, 4],
  :STRING=>[:reduce, 4],
  :LBRACK=>[:reduce, 4],
  :NUMBER=>[:reduce, 4],
  :CHARACTER=>[:reduce, 4],
  :RPAREN=>[:reduce, 4]},
 {:"$"=>[:reduce, 13],
  :STAR=>[:reduce, 13],
  :PLUS=>[:reduce, 13],
  :OPTIONAL=>[:reduce, 13],
  :UNION=>[:reduce, 13],
  :INTERSECT=>[:reduce, 13],
  :SDIFFERENCE=>[:reduce, 13],
  :DIFFERENCE=>[:reduce, 13],
  :LPAREN=>[:reduce, 13],
  :STRING=>[:reduce, 13],
  :LBRACK=>[:reduce, 13],
  :NUMBER=>[:reduce, 13],
  :CHARACTER=>[:reduce, 13],
  :RPAREN=>[:reduce, 13]},
 {:"$"=>[:reduce, 18],
  :STAR=>[:reduce, 18],
  :PLUS=>[:reduce, 18],
  :OPTIONAL=>[:reduce, 18],
  :UNION=>[:reduce, 18],
  :INTERSECT=>[:reduce, 18],
  :SDIFFERENCE=>[:reduce, 18],
  :DIFFERENCE=>[:reduce, 18],
  :LPAREN=>[:reduce, 18],
  :STRING=>[:reduce, 18],
  :LBRACK=>[:reduce, 18],
  :NUMBER=>[:reduce, 18],
  :CHARACTER=>[:reduce, 18],
  :RPAREN=>[:reduce, 18]},
 {:RBRACK=>[:reduce, 26]},
 {:"contain.char"=>[:state, 41],
  :CHARACTER=>[:state, 27],
  :NUMBER=>[:state, 28],
  :ESCAPED=>[:state, 29]},
 {:"$"=>[:reduce, 21],
  :STAR=>[:reduce, 21],
  :PLUS=>[:reduce, 21],
  :OPTIONAL=>[:reduce, 21],
  :UNION=>[:reduce, 21],
  :INTERSECT=>[:reduce, 21],
  :SDIFFERENCE=>[:reduce, 21],
  :DIFFERENCE=>[:reduce, 21],
  :LPAREN=>[:reduce, 21],
  :STRING=>[:reduce, 21],
  :LBRACK=>[:reduce, 21],
  :NUMBER=>[:reduce, 21],
  :CHARACTER=>[:reduce, 21],
  :RPAREN=>[:reduce, 21]},
 {:RBRACK=>[:reduce, 28],
  :CHARACTER=>[:reduce, 28],
  :NUMBER=>[:reduce, 28],
  :ESCAPED=>[:reduce, 28],
  :DIFFERENCE=>[:reduce, 28]}]
.freeze # >

# A list of all of the productions.  Only includes the left-hand side,
# the number of tokens on the right-hand side, and the block to call
# on reduction.
#
# @return [Array<Array<(Symbol, Numeric, Proc)>>]
PRODUCTIONS  = [[:$start, 2, proc { |_| _ }],
[:expression, 1, proc { |_|    [_]          }],
[:expression, 2, proc { |a, b| b.unshift(a) }],
[:group, 2, proc { |a, b|    compile_modifier(b, a) }],
[:group, 3, proc { |a, b, c| compile_binop(b, a, c) }],
[:group, 1, proc { |_| _ }],
[:modifier, 1, proc { |_| _[0] }],
[:modifier, 1, proc { |_| _[0] }],
[:modifier, 1, proc { |_| _[0] }],
[:binop, 1, proc { |_| _[0] }],
[:binop, 1, proc { |_| _[0] }],
[:binop, 1, proc { |_| _[0] }],
[:binop, 1, proc { |_| _[0] }],
[:value, 3, proc { |_, a, _| compile_paren(a)      }],
[:value, 1, proc { |_|       compile_string(_)     }],
[:value, 1, proc { |_|       compile_contain(_)    }],
[:value, 1, proc { |_|       compile_number(_)     }],
[:value, 1, proc { |_|       compile_identifier(_) }],
[:contain, 3, proc { |_, a, _| a }],
[:identifier, 2, proc { |a, b| b.unshift(a)             }],
[:chars, 1, proc { |_|    [_]                      }],
[:chars, 2, proc { |a, b| b.unshift(a)             }],
[:char, 1, proc { |_| _ }],
[:char, 1, proc { |_| _ }],
[:char, 1, proc { |_| _ }],
[:"contain.parts", 1, proc { |_|    [_]          }],
[:"contain.parts", 2, proc { |a, b| b.unshift(a) }],
[:"contain.part", 1, proc { |_| _ }],
[:"contain.part", 3, proc { |a, b, c| [:SET, a[1], c[1]] }],
[:"contain.part", 1, proc { |_| _ }],
[:"contain.char", 1, proc { |_| _ }],
[:"contain.char", 1, proc { |_| _ }],
[:"contain.char", 1, proc { |_| _ }]].freeze # >

# Runs the parser.
#
# @param input [Array<Object>] the input to run the parser over.
# @return [Object] the result of the accept.
def parse(input)
  stack = []
  stack.push([nil, 0])
  input = input.dup
  last  = nil

  until stack.empty? do
    peek_token = if input.empty?
      :"$"
    else
      type(input.first)
    end

    action = ACTION_TABLE[stack.last.last].fetch(peek_token)
    case action.first
    when :accept
      production = PRODUCTIONS[action.last]
      last       = stack.pop(production[1]).first.first
      stack.pop
    when :reduce
      production = PRODUCTIONS[action.last]
      removing   = stack.pop(production[1])
      value = instance_exec(*removing.map(&:first), &production[2])
      goto  = ACTION_TABLE[stack.last.last][production[0]]
      stack.push([value, goto.last])
    when :state
      stack.push([input.shift, action.last])
    else
      raise
    end
  end

  last
end


      def type(token)
        token[0].to_s.upcase.intern
      end
    end
  end
end
